# Generated by Django 3.1 on 2021-01-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chambernumber', models.CharField(max_length=20)),
                ('batnumber', models.CharField(max_length=10)),
                ('typeChambre', models.CharField(choices=[('individuel', 'individuel'), ('double', 'double')], default='individuel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('typeEtudiant', models.CharField(max_length=50)),
                ('bourse', models.CharField(max_length=20, null=True)),
                ('addresse', models.CharField(max_length=100, null=True)),
                ('chambre', models.ManyToManyField(null=True, to='campus.Chambre')),
            ],
        ),
    ]
