# Generated by Django 3.1 on 2021-01-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='chambre',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='chambre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.chambre'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='typeEtudiant',
            field=models.CharField(choices=[('Boursier', 'Boursier'), ('Non Boursier', 'Non Boursier')], default='Non Boursier', max_length=50),
        ),
    ]
