# Generated by Django 3.1 on 2021-01-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_auto_20210114_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='addresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='bourse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.chambre'),
        ),
    ]
