# Generated by Django 3.1 on 2021-01-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20210114_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='typeEtudiant',
            field=models.CharField(choices=[('Boursier logé', 'Boursier logé'), ('Boursier non logé', 'Boursier non logé'), ('Non Boursier', 'Non Boursier')], default='Non Boursier', max_length=50),
        ),
    ]
