# Generated by Django 3.1 on 2021-01-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_auto_20210115_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
